# Site settings
title: The Physical Web

# Ocupop site
# baseurl: "/physical-web" # the subpath of your site, e.g. /blog
# url: "http://ocupopdev.com" # the base hostname & protocol for your site

# Localhost
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:4000/" # the base hostname & protocol for your site

# Production to animohan github
# baseurl: "/Physical-Web-Site"
# url: "https://anirudhcmohan.github.io"

# Production to physical web github
baseurl: "/physical-web"
url: "https://google.github.io"
permalink: /:path

# Build settings
safe: false
source: src

# Test environment
# destination: publish

# Production environment
destination: publish-pw-site

markdown: kramdown

include: ["_pages"]
exclude: ["vendor"]

gems:
- jekyll-assets
- jekyll-toc

assets:
  compress:
    css: true # default - development: false, production: true
    js: true # default - development: false, production: true
  cache: false # default: .asset-cache
  # cdn: https://cdn.example.com
  # skip_baseurl_with_cdn: false
  # skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.jpg"
    - "*.eot"
    - "*.ttf"
    - "*.woff"
    - "*.svg"
    - "*.scss"
  #   - "bundle.css"
  digest: true
  sources:
    - _assets/bower
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/media
    - _assets/fonts
  features:
    liquid: true # default: false
    automatic_img_size: true # default: true
    automatic_img_alt : true # default: true